name: docs

on:
  push:
    branches: 'main'

jobs:
    deploy-docs:
        if: (github.event_name == 'release') || (github.event_name == 'push' && github.ref == 'refs/heads/main')

        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
          - name: checkout
            uses: actions/checkout@v4

          - name: Install uv
            uses: astral-sh/setup-uv@v3

          - name: "Set up Python"
            uses: actions/setup-python@v5
            with:
              python-version-file: ".python-version"

          - name: Install the project
            run: uv sync --only-group docs

          - name: deploy-to-gh-pages
            run: uv run mkdocs gh-deploy --force
